-- ============================================================
-- V10_40__create_med_audit_tables_phase2.sql
-- Tablas de auditoría Hibernate Envers para entidades Phase 2.
-- Creadas automáticamente por Envers en validate mode; este script
-- las pre-crea para evitar arranques fallidos y controlar la estructura.
-- ============================================================

-- Audit: MED_DEPARTMENT_UNIT
CREATE TABLE IF NOT EXISTS MED_DEPARTMENT_UNIT_AUD (
    ID              BIGINT       NOT NULL,
    REV             BIGINT       NOT NULL,
    REVTYPE         TINYINT,
    TENANT_CODE     VARCHAR(50),
    TENANT_ID       BIGINT,
    EXTERNAL_ID     VARCHAR(36),
    VERSION         BIGINT,
    IS_DELETED      TINYINT(1),
    NAME            VARCHAR(150),
    CODE            VARCHAR(30),
    FLOOR           VARCHAR(20),
    CONTACT_PHONE   VARCHAR(50),
    DESCRIPTION     TEXT,
    IS_ACTIVE       TINYINT(1),
    MAX_CAPACITY    INT,
    IS_CLINICAL     TINYINT(1),
    COST_CENTER     VARCHAR(50),
    FK_ID_PARENT_UNIT   BIGINT,
    FK_ID_UNIT_HEAD     BIGINT,
    CREATED_BY          VARCHAR(100),
    CREATED_DATE        DATETIME(6),
    LAST_MODIFIED_BY    VARCHAR(100),
    LAST_MODIFIED_DATE  DATETIME(6),
    PRIMARY KEY (ID, REV),
    CONSTRAINT FK_MED_DEPT_UNIT_AUD_REV FOREIGN KEY (REV) REFERENCES DMN_AUDIT_REVISION(REV)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Audit: MED_ROOM
CREATE TABLE IF NOT EXISTS MED_ROOM_AUD (
    ID              BIGINT       NOT NULL,
    REV             BIGINT       NOT NULL,
    REVTYPE         TINYINT,
    TENANT_CODE     VARCHAR(50),
    TENANT_ID       BIGINT,
    EXTERNAL_ID     VARCHAR(36),
    VERSION         BIGINT,
    IS_DELETED      TINYINT(1),
    FK_ID_DEPT_UNIT BIGINT,
    ROOM_NUMBER     VARCHAR(20),
    IS_PRIVATE      TINYINT(1),
    ROOM_TYPE       VARCHAR(30),
    BLOCK_FLOOR     INT,
    BLOCK_CODE      VARCHAR(20),
    DESCRIPTION     TEXT,
    CLEANING_STATUS VARCHAR(30),
    IS_ACTIVE       TINYINT(1),
    CREATED_BY      VARCHAR(100),
    CREATED_DATE    DATETIME(6),
    LAST_MODIFIED_BY VARCHAR(100),
    LAST_MODIFIED_DATE DATETIME(6),
    PRIMARY KEY (ID, REV),
    CONSTRAINT FK_ROOM_AUD_REV FOREIGN KEY (REV) REFERENCES DMN_AUDIT_REVISION(REV)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Audit: MED_BED
CREATE TABLE IF NOT EXISTS MED_BED_AUD (
    ID              BIGINT       NOT NULL,
    REV             BIGINT       NOT NULL,
    REVTYPE         TINYINT,
    TENANT_CODE     VARCHAR(50),
    TENANT_ID       BIGINT,
    EXTERNAL_ID     VARCHAR(36),
    VERSION         BIGINT,
    IS_DELETED      TINYINT(1),
    FK_ID_ROOM      BIGINT,
    BED_NUMBER      VARCHAR(20),
    BED_CODE        VARCHAR(30),
    IS_OCCUPIED     TINYINT(1),
    STATUS          VARCHAR(30),
    DESCRIPTION     TEXT,
    MAINTENANCE_DUE DATE,
    IS_ACTIVE       TINYINT(1),
    CREATED_BY      VARCHAR(100),
    CREATED_DATE    DATETIME(6),
    LAST_MODIFIED_BY VARCHAR(100),
    LAST_MODIFIED_DATE DATETIME(6),
    PRIMARY KEY (ID, REV),
    CONSTRAINT FK_BED_AUD_REV FOREIGN KEY (REV) REFERENCES DMN_AUDIT_REVISION(REV)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Audit: MED_USER_PROFILE
CREATE TABLE IF NOT EXISTS MED_USER_PROFILE_AUD (
    ID              BIGINT       NOT NULL,
    REV             BIGINT       NOT NULL,
    REVTYPE         TINYINT,
    TENANT_CODE     VARCHAR(50),
    TENANT_ID       BIGINT,
    EXTERNAL_ID     VARCHAR(36),
    VERSION         BIGINT,
    IS_DELETED      TINYINT(1),
    BIOGRAPHY       VARCHAR(2000),
    PHOTO           LONGBLOB,
    CREATED_BY      VARCHAR(100),
    CREATED_DATE    DATETIME(6),
    LAST_MODIFIED_BY VARCHAR(100),
    LAST_MODIFIED_DATE DATETIME(6),
    PRIMARY KEY (ID, REV),
    CONSTRAINT FK_USER_PROFILE_AUD_REV FOREIGN KEY (REV) REFERENCES DMN_AUDIT_REVISION(REV)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Audit: MED_EMPLOYEE
CREATE TABLE IF NOT EXISTS MED_EMPLOYEE_AUD (
    ID                  BIGINT       NOT NULL,
    REV                 BIGINT       NOT NULL,
    REVTYPE             TINYINT,
    TENANT_CODE         VARCHAR(50),
    TENANT_ID           BIGINT,
    EXTERNAL_ID         VARCHAR(36),
    VERSION             BIGINT,
    IS_DELETED          TINYINT(1),
    FK_ID_PERSON        BIGINT,
    USER_ID             BIGINT,
    FK_ID_DEPT_UNIT     BIGINT,
    EMPLOYEE_CODE       VARCHAR(50),
    EMPLOYEE_TYPE       VARCHAR(40),
    EMPLOYEE_STATUS     VARCHAR(30),
    PROFESSIONAL_ROLE   VARCHAR(50),
    JOB_POSITION        VARCHAR(120),
    HIRE_DATE           DATE,
    SALARY              DECIMAL(12,2),
    EMPLOYMENT_TYPE     VARCHAR(50),
    WORK_SHIFT          VARCHAR(50),
    EMERGENCY_CONTACT   VARCHAR(200),
    CREATED_BY          VARCHAR(100),
    CREATED_DATE        DATETIME(6),
    LAST_MODIFIED_BY    VARCHAR(100),
    LAST_MODIFIED_DATE  DATETIME(6),
    PRIMARY KEY (ID, REV),
    CONSTRAINT FK_EMPLOYEE_AUD_REV FOREIGN KEY (REV) REFERENCES DMN_AUDIT_REVISION(REV)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Audit: MED_NURSE
CREATE TABLE IF NOT EXISTS MED_NURSE_AUD (
    ID                  BIGINT       NOT NULL,
    REV                 BIGINT       NOT NULL,
    REVTYPE             TINYINT,
    TENANT_CODE         VARCHAR(50),
    TENANT_ID           BIGINT,
    EXTERNAL_ID         VARCHAR(36),
    VERSION             BIGINT,
    IS_DELETED          TINYINT(1),
    FK_ID_PERSON        BIGINT,
    USER_ID             BIGINT,
    FK_ID_DEPT_UNIT     BIGINT,
    FK_ID_USERPROFILE   BIGINT,
    NURSE_LICENSE       VARCHAR(100),
    NURSE_RANK          VARCHAR(100),
    WORK_SHIFT          VARCHAR(50),
    LICENSE_EXPIRY      DATE,
    HIRE_DATE           DATE,
    CONTRACT_TYPE       VARCHAR(50),
    EMERGENCY_CONTACT   VARCHAR(200),
    CREATED_BY          VARCHAR(100),
    CREATED_DATE        DATETIME(6),
    LAST_MODIFIED_BY    VARCHAR(100),
    LAST_MODIFIED_DATE  DATETIME(6),
    PRIMARY KEY (ID, REV),
    CONSTRAINT FK_NURSE_AUD_REV FOREIGN KEY (REV) REFERENCES DMN_AUDIT_REVISION(REV)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Audit: MED_PROFESSIONAL_INFO
CREATE TABLE IF NOT EXISTS MED_PROFESSIONAL_INFO_AUD (
    ID                  BIGINT       NOT NULL,
    REV                 BIGINT       NOT NULL,
    REVTYPE             TINYINT,
    TENANT_CODE         VARCHAR(50),
    TENANT_ID           BIGINT,
    EXTERNAL_ID         VARCHAR(36),
    VERSION             BIGINT,
    IS_DELETED          TINYINT(1),
    FK_ID_PERSON        BIGINT,
    ORGANIZATION_ID     BIGINT,
    PERIOD_START_DATE   DATE,
    PERIOD_END_DATE     DATE,
    IS_CURRENT          TINYINT(1),
    ROLE_CONTEXT        VARCHAR(50),
    POSITION            VARCHAR(100),
    DEPARTMENT          VARCHAR(100),
    EMPLOYEE_ID_REF     VARCHAR(50),
    LICENSE_NUMBER      VARCHAR(100),
    EXPERIENCE_AT_START INT,
    CONTRACT_TYPE       VARCHAR(50),
    WORK_SCHEDULE       VARCHAR(100),
    SALARY_GRADE        VARCHAR(50),
    SUPERVISOR          VARCHAR(100),
    PERFORMANCE_RATING  DECIMAL(3,1),
    NOTES               TEXT,
    CREATED_BY          VARCHAR(100),
    CREATED_DATE        DATETIME(6),
    LAST_MODIFIED_BY    VARCHAR(100),
    LAST_MODIFIED_DATE  DATETIME(6),
    PRIMARY KEY (ID, REV),
    CONSTRAINT FK_PROF_INFO_AUD_REV FOREIGN KEY (REV) REFERENCES DMN_AUDIT_REVISION(REV)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
