-- *******************************************************
-- Script de creación de tabla MGT_SUPER_ADMIN
-- *******************************************************
CREATE TABLE IF NOT EXISTS MGT_SUPER_ADMIN (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TENANT_CODE VARCHAR(50) NOT NULL DEFAULT 'SYSTEM',
    TENANT_ID BIGINT NOT NULL DEFAULT 0,
    EXTERNAL_ID VARCHAR(36) UNIQUE,
    VERSION BIGINT DEFAULT 0 NOT NULL,
    FK_ID_PERSON BIGINT NOT NULL,
    FK_ID_USER BIGINT NOT NULL,
    IS_DELETED TINYINT(1) DEFAULT 0 NOT NULL,
    LEVEL ENUM('LEVEL_1','LEVEL_2','LEVEL_3') NOT NULL,
    GLOBAL_ACCESS BOOLEAN NOT NULL DEFAULT FALSE,

    -- Auditoría
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE DATETIME(6) NOT NULL,
    LAST_MODIFIED_BY VARCHAR(100),
    LAST_MODIFIED_DATE DATETIME(6),

    CONSTRAINT FK_SUPER_ADMIN_PERSON FOREIGN KEY (FK_ID_PERSON) REFERENCES DMN_PERSON(ID) ON DELETE CASCADE,
    CONSTRAINT FK_SUPER_ADMIN_USER FOREIGN KEY (FK_ID_USER) REFERENCES AUT_USER(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
