-- *******************************************************
-- Script de creación de tabla MGT_TENANT_ADMIN
-- *******************************************************

CREATE TABLE IF NOT EXISTS MGT_TENANT_ADMIN (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    TENANT_CODE VARCHAR(50) NOT NULL,
    TENANT_ID BIGINT NOT NULL,
    EXTERNAL_ID VARCHAR(36) UNIQUE,
    VERSION BIGINT DEFAULT 0 NOT NULL,
    FK_ID_PERSON BIGINT NOT NULL,
    FK_ID_USER BIGINT NOT NULL,
    IS_DELETED TINYINT(1) DEFAULT 0 NOT NULL,
    ADMIN_LEVEL ENUM('LEVEL_1','LEVEL_2','LEVEL_3') NOT NULL,

    -- Auditoría
    CREATED_BY VARCHAR(100) NOT NULL,
    CREATED_DATE DATETIME(6) NOT NULL,
    LAST_MODIFIED_BY VARCHAR(100),
    LAST_MODIFIED_DATE DATETIME(6),

    CONSTRAINT FK_TENANT_ADMIN_PERSON FOREIGN KEY (FK_ID_PERSON) REFERENCES DMN_PERSON(ID) ON DELETE CASCADE,
    CONSTRAINT FK_TENANT_ADMIN_TENANT FOREIGN KEY (TENANT_ID) REFERENCES DMN_TENANT(ID)
    ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT FK_TENANT_ADMIN_USER FOREIGN KEY (FK_ID_USER) REFERENCES AUT_USER(ID)
    ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT UK_TENANT_ADMIN_USER UNIQUE (FK_ID_USER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX IDX_TENANT_ADMIN_TENANT ON MGT_TENANT_ADMIN (TENANT_ID);
