CREATE TABLE IF NOT EXISTS AUT_ROLE_PERMISSION (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    FK_ID_ROLE BIGINT NOT NULL,
    FK_ID_PERMISSION BIGINT NOT NULL,
    CONSTRAINT UK_ROLE_PERMISSION UNIQUE (FK_ID_ROLE, FK_ID_PERMISSION),
    CONSTRAINT FK_ROLE_PERMISSION_ROLE FOREIGN KEY (FK_ID_ROLE) REFERENCES AUT_ROLE (ID),
    CONSTRAINT FK_ROLE_PERMISSION_PERMISSION FOREIGN KEY (FK_ID_PERMISSION) REFERENCES AUT_PERMISSION (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

